"""
QUANTUMANIA - Google Gemini AI Tutor Provider
Phase 5: AI Quantum Tutor
Direct REST API client using httpx with graceful fallback
"""

import httpx
from typing import Dict, Any
from app.core.config import settings
from app.schemas.tutor import TutorRequest, TutorResponse
from app.services.tutor.prompts import TUTOR_SYSTEM_PROMPT
from app.services.tutor.providers.base import BaseAIProvider
from app.services.tutor.providers.deterministic_provider import DeterministicTutorProvider


class GeminiTutorProvider(BaseAIProvider):
    def __init__(self):
        self.fallback_provider = DeterministicTutorProvider()

    async def generate_response(
        self,
        request: TutorRequest,
        context_prompt: str,
        metadata: Dict[str, Any]
    ) -> TutorResponse:
        api_key = settings.GEMINI_API_KEY
        if not api_key:
            # Fall back to deterministic pedagogical engine if key not configured
            return await self.fallback_provider.generate_response(request, context_prompt, metadata)

        model = settings.AI_MODEL or "gemini-1.5-flash"
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"

        payload = {
            "system_instruction": {
                "parts": [{"text": TUTOR_SYSTEM_PROMPT}]
            },
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": context_prompt}]
                }
            ],
            "generationConfig": {
                "temperature": settings.TUTOR_TEMPERATURE,
                "maxOutputTokens": 1500
            }
        }

        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                response = await client.post(url, json=payload)

            if response.status_code != 200:
                # Log and fallback gracefully
                return await self.fallback_provider.generate_response(request, context_prompt, metadata)

            data = response.json()
            candidates = data.get("candidates", [])
            if not candidates:
                return await self.fallback_provider.generate_response(request, context_prompt, metadata)

            parts = candidates[0].get("content", {}).get("parts", [])
            reply_text = "".join(p.get("text", "") for p in parts).strip()

            if not reply_text:
                return await self.fallback_provider.generate_response(request, context_prompt, metadata)

            meta_with_provider = {**metadata, "provider": "gemini", "model": model}
            return TutorResponse(
                mode=request.mode,
                message=reply_text,
                key_points=["Generated by AI Quantum Tutor"],
                next_step="Try applying the tutor's advice in your circuit.",
                follow_up_question="Do you have any questions about this explanation?",
                context_used=meta_with_provider
            )

        except Exception:
            # Under any network, SSL, or timeout failure, return ground-truth fallback
            return await self.fallback_provider.generate_response(request, context_prompt, metadata)
