"""
QUANTUMANIA - OpenAI AI Tutor Provider
Phase 5: AI Quantum Tutor
Direct REST API client using httpx with graceful fallback
"""

import httpx
from typing import Dict, Any
from app.core.config import settings
from app.schemas.tutor import TutorRequest, TutorResponse
from app.services.tutor.prompts import TUTOR_SYSTEM_PROMPT
from app.services.tutor.providers.base import BaseAIProvider
from app.services.tutor.providers.deterministic_provider import DeterministicTutorProvider


class OpenAITutorProvider(BaseAIProvider):
    def __init__(self):
        self.fallback_provider = DeterministicTutorProvider()

    async def generate_response(
        self,
        request: TutorRequest,
        context_prompt: str,
        metadata: Dict[str, Any]
    ) -> TutorResponse:
        api_key = settings.OPENAI_API_KEY
        if not api_key:
            return await self.fallback_provider.generate_response(request, context_prompt, metadata)

        model = "gpt-4o-mini" if "gpt" in settings.AI_MODEL.lower() else "gpt-4o"
        url = "https://api.openai.com/v1/chat/completions"

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": TUTOR_SYSTEM_PROMPT},
                {"role": "user", "content": context_prompt}
            ],
            "temperature": settings.TUTOR_TEMPERATURE,
            "max_tokens": 1500
        }

        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                response = await client.post(url, headers=headers, json=payload)

            if response.status_code != 200:
                return await self.fallback_provider.generate_response(request, context_prompt, metadata)

            data = response.json()
            choices = data.get("choices", [])
            if not choices:
                return await self.fallback_provider.generate_response(request, context_prompt, metadata)

            reply_text = choices[0].get("message", {}).get("content", "").strip()
            if not reply_text:
                return await self.fallback_provider.generate_response(request, context_prompt, metadata)

            meta_with_provider = {**metadata, "provider": "openai", "model": model}
            return TutorResponse(
                mode=request.mode,
                message=reply_text,
                key_points=["Generated by AI Quantum Tutor"],
                next_step="Try applying the tutor's advice in your circuit.",
                follow_up_question="Do you have any questions about this explanation?",
                context_used=meta_with_provider
            )

        except Exception:
            return await self.fallback_provider.generate_response(request, context_prompt, metadata)
